import type { Metadata } from "next";
import "./globals.css";

// For Layout Components
import { Navbar } from "./layout/Navbar/Navbar";
import { Footer } from "./layout/Footer/Footer";


export const metadata: Metadata = {
  title: {
    template: "%s - Easy VR",
    default: "Where Virtuality Meets Reality",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
